### ISSUE TITLE
Cannot implement NoiseConfig, noise::ConfigError is public for crate but is not exposed in lib.rs

### ISSUE THREAD

**Issue by edouardparis** [digitalbitbox/bitbox-api-rs#44]
Also is it possible to add `#[derive(Clone)]` to NoiseConfigData ?

**Comment by benma** [comment]
Could you implement the noise config thing using this repo as a git-dep with all the fixes needed and then make a PR of the changes? So I can avoid making many small point releases and speed things up.

Unless you are sure this is the last change needed :smile:

**Comment by edouardparis** [comment]
yes, sure, I should have done that

**Comment by benma** [comment]
@edouardparis thanks! published as v0.1.8
