### ISSUE TITLE
BTC Sign Message

### ISSUE THREAD

**Issue by davidleomay** [digitalbitbox/bitbox-api-rs#49]
I just saw that the `btcSignMessage` call is missing. Do you plan to add it?

**Comment by benma** [comment]
Indeed - yes, we will add it.

**Comment by davidleomay** [comment]
Cool, thanks!

**Comment by benma** [comment]
@davidleomay this is now published at https://www.npmjs.com/package/bitbox-api 0.2.0

**Comment by davidleomay** [comment]
Thanks for the hint @benma. I just tried it an I think there is an error in the typing @asi345.

From `bitbox_api.d.ts` I get

```ts
type BtcSignMessageSignature = {
  sig: Uint8Array,
  recid: bigint,
  electrumSig65: Uint8Array,
}
```

but the response from `btcSignMessage` actually is

```ts
{ sig: Array(64), recid: 0, electrum_sig65: Array(65) }
```

**Comment by benma** [comment]
@asi345 looks like this review comment somehow slipped through the cracks https://github.com/digitalbitbox/bitbox-api-rs/pull/54#discussion_r1373270936 - can you take a look?

**Comment by asi345** [comment]
You're right, I missed that since I was doing camel case manually. Take a look here #56 , where I addressed this issue.

**Comment by asi345** [comment]
@davidleomay  a new version is now published at https://www.npmjs.com/package/bitbox-api 0.2.1, where this issue was solved.

**Comment by davidleomay** [comment]
@asi345 awesome, thanks 🚀 it works now!
