### ISSUE TITLE
Bug in error messages in sandbox UI

### ISSUE THREAD

**Issue by asi345** [digitalbitbox/bitbox-api-rs#51]
The error message does not fit into the message box in BitBox sandbox UI, it exceeds the screen borders. Therefore they can not be fully read. Attaching a screenshot for this below:
<img width="1424" alt="Screenshot 2023-10-18 at 13 58 10" src="https://github.com/digitalbitbox/bitbox-api-rs/assets/56401493/32b4fdf1-ad81-4efb-b8ed-6d8dd2d3bb02">

**Comment by benma** [comment]
If the error is of type `bitbox.Error`, it would be nice to render the code and message separately instead of the JSON.
